"""B03 auth: ma_xac_thuc + phu_huynh_id

Revision ID: 2257fa958ec4
Revises: c39637a57594
Create Date: 2026-06-26 22:59:48.004241

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2257fa958ec4"
down_revision: Union[str, None] = "c39637a57594"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ma_xac_thuc",
        sa.Column("dinh_danh", sa.String(length=255), nullable=False),
        sa.Column("ma_hash", sa.String(length=255), nullable=False),
        sa.Column("muc_dich", sa.Enum("dang_ky", "dang_nhap", name="mucdichotp"), nullable=False),
        sa.Column("het_han", sa.DateTime(), nullable=False),
        sa.Column("da_dung", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ma_xac_thuc", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ma_xac_thuc_dinh_danh"), ["dinh_danh"], unique=False)

    with op.batch_alter_table("nguoi_dung", schema=None) as batch_op:
        batch_op.add_column(sa.Column("phu_huynh_id", sa.String(length=32), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_nguoi_dung_phu_huynh_id"), ["phu_huynh_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_nguoi_dung_phu_huynh", "nguoi_dung", ["phu_huynh_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nguoi_dung", schema=None) as batch_op:
        batch_op.drop_constraint("fk_nguoi_dung_phu_huynh", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_nguoi_dung_phu_huynh_id"))
        batch_op.drop_column("phu_huynh_id")

    with op.batch_alter_table("ma_xac_thuc", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ma_xac_thuc_dinh_danh"))

    op.drop_table("ma_xac_thuc")
    # ### end Alembic commands ###
