"""B27 review: hang_doi_duyet

Revision ID: 70c65a994b48
Revises: fde45a745e8d
Create Date: 2026-06-27 00:24:19.899591

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "70c65a994b48"
down_revision: Union[str, None] = "fde45a745e8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hang_doi_duyet",
        sa.Column("loai", sa.String(length=50), nullable=False),
        sa.Column("noi_dung", sa.Text(), nullable=False),
        sa.Column("chi_tiet", sa.JSON(), nullable=True),
        sa.Column(
            "trang_thai", sa.Enum("cho_duyet", "da_duyet", name="trangthaiduyet"), nullable=False
        ),
        sa.Column("ket_luan_nguoi", sa.Text(), nullable=True),
        sa.Column("nguoi_duyet_id", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["nguoi_duyet_id"],
            ["nguoi_dung.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hang_doi_duyet")
    # ### end Alembic commands ###
