"""B30 spaced: khai_niem_on

Revision ID: b4a123c47c07
Revises: 2d30ae35856e
Create Date: 2026-06-27 00:32:50.806862

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b4a123c47c07"
down_revision: Union[str, None] = "2d30ae35856e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "khai_niem_on",
        sa.Column("nguoi_dung_id", sa.String(length=32), nullable=False),
        sa.Column("khai_niem", sa.String(length=255), nullable=False),
        sa.Column("so_lan_sai", sa.Integer(), nullable=False),
        sa.Column("so_lan_on", sa.Integer(), nullable=False),
        sa.Column("lan_on_ke_tiep", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["nguoi_dung_id"],
            ["nguoi_dung.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nguoi_dung_id", "khai_niem", name="uq_khai_niem_on_nguoi_kn"),
    )
    with op.batch_alter_table("khai_niem_on", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_khai_niem_on_nguoi_dung_id"), ["nguoi_dung_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("khai_niem_on", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_khai_niem_on_nguoi_dung_id"))

    op.drop_table("khai_niem_on")
    # ### end Alembic commands ###
