"""B02 init schema SRS-7

Revision ID: c39637a57594
Revises:
Create Date: 2026-06-26 22:43:54.002237

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c39637a57594"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "de_bai",
        sa.Column("mon", sa.String(length=50), nullable=False),
        sa.Column("cap_do", sa.Enum("thpt", "olympiad", name="capdo"), nullable=False),
        sa.Column("lop", sa.Integer(), nullable=True),
        sa.Column("chuong", sa.String(length=100), nullable=True),
        sa.Column(
            "do_kho",
            sa.Enum("nhan_biet", "thong_hieu", "van_dung", "van_dung_cao", name="dokho"),
            nullable=True,
        ),
        sa.Column("nguon", sa.String(length=255), nullable=True),
        sa.Column("de_latex", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "nguoi_dung",
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("so_dien_thoai", sa.String(length=20), nullable=True),
        sa.Column("hashed_password", sa.String(length=255), nullable=True),
        sa.Column(
            "vai_tro",
            sa.Enum("hoc_sinh", "phu_huynh", "hlv", "bien_tap", "quan_tri", name="vaitro"),
            nullable=False,
        ),
        sa.Column(
            "trang_thai",
            sa.Enum("cho_xac_thuc", "hoat_dong", "khoa", name="trangthainguoidung"),
            nullable=False,
        ),
        sa.Column("la_vi_thanh_nien", sa.Boolean(), nullable=False),
        sa.Column("dong_y_phu_huynh", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_nguoi_dung_email"), "nguoi_dung", ["email"], unique=True)
    op.create_index(
        op.f("ix_nguoi_dung_so_dien_thoai"), "nguoi_dung", ["so_dien_thoai"], unique=True
    )
    op.create_table(
        "goi",
        sa.Column("nguoi_dung_id", sa.String(length=32), nullable=False),
        sa.Column("loai", sa.Enum("free", "standard", "premium", name="loaigoi"), nullable=False),
        sa.Column(
            "trang_thai",
            sa.Enum("hoat_dong", "het_han", "huy", name="trangthaigoi"),
            nullable=False,
        ),
        sa.Column("bat_dau", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ket_thuc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["nguoi_dung_id"],
            ["nguoi_dung.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_goi_nguoi_dung_id"), "goi", ["nguoi_dung_id"], unique=False)
    op.create_table(
        "han_muc",
        sa.Column("nguoi_dung_id", sa.String(length=32), nullable=False),
        sa.Column("ngay", sa.Date(), nullable=False),
        sa.Column("so_cau_da_dung", sa.Integer(), nullable=False),
        sa.Column("gioi_han", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["nguoi_dung_id"],
            ["nguoi_dung.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nguoi_dung_id", "ngay", name="uq_han_muc_nguoi_ngay"),
    )
    op.create_index(op.f("ix_han_muc_nguoi_dung_id"), "han_muc", ["nguoi_dung_id"], unique=False)
    op.create_table(
        "ho_so_hoc_sinh",
        sa.Column("nguoi_dung_id", sa.String(length=32), nullable=False),
        sa.Column("phan_khuc", sa.Enum("dai_tra", "tinh_hoa", name="phankhuc"), nullable=False),
        sa.Column("lop", sa.Integer(), nullable=True),
        sa.Column("mon", sa.String(length=50), nullable=True),
        sa.Column("doi_tuyen", sa.String(length=100), nullable=True),
        sa.Column(
            "muc_do", sa.Enum("yeu", "trung_binh", "kha_gioi", name="mucdohoc"), nullable=True
        ),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["nguoi_dung_id"],
            ["nguoi_dung.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nguoi_dung_id"),
    )
    op.create_table(
        "hoi_thoai",
        sa.Column("nguoi_dung_id", sa.String(length=32), nullable=False),
        sa.Column("phan_khuc", sa.Enum("dai_tra", "tinh_hoa", name="phankhuc"), nullable=False),
        sa.Column("chu_de", sa.String(length=255), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["nguoi_dung_id"],
            ["nguoi_dung.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_hoi_thoai_nguoi_dung_id"), "hoi_thoai", ["nguoi_dung_id"], unique=False
    )
    op.create_table(
        "loi_giai",
        sa.Column("de_bai_id", sa.String(length=32), nullable=False),
        sa.Column("cac_buoc", sa.JSON(), nullable=True),
        sa.Column("dap_so", sa.String(length=255), nullable=True),
        sa.Column("nguon", sa.String(length=255), nullable=True),
        sa.Column("la_mau", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["de_bai_id"],
            ["de_bai.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_loi_giai_de_bai_id"), "loi_giai", ["de_bai_id"], unique=False)
    op.create_table(
        "thanh_toan",
        sa.Column("nguoi_dung_id", sa.String(length=32), nullable=False),
        sa.Column("so_tien", sa.Integer(), nullable=False),
        sa.Column(
            "phuong_thuc",
            sa.Enum("vietqr", "momo", "zalopay", "vnpay", name="phuongthucthanhtoan"),
            nullable=False,
        ),
        sa.Column(
            "trang_thai",
            sa.Enum("cho", "thanh_cong", "that_bai", name="trangthaithanhtoan"),
            nullable=False,
        ),
        sa.Column("ma_giao_dich", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["nguoi_dung_id"],
            ["nguoi_dung.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ma_giao_dich"),
    )
    op.create_index(
        op.f("ix_thanh_toan_nguoi_dung_id"), "thanh_toan", ["nguoi_dung_id"], unique=False
    )
    op.create_table(
        "phan_anh",
        sa.Column("nguoi_gui_id", sa.String(length=32), nullable=True),
        sa.Column("an_danh", sa.Boolean(), nullable=False),
        sa.Column(
            "chu_de",
            sa.Enum(
                "loi_loi_giai", "gop_y", "thanh_toan", "trai_nghiem", "khac", name="chudephananh"
            ),
            nullable=False,
        ),
        sa.Column("tieu_de", sa.String(length=255), nullable=False),
        sa.Column("noi_dung", sa.Text(), nullable=False),
        sa.Column("anh_url", sa.String(length=500), nullable=True),
        sa.Column(
            "trang_thai",
            sa.Enum("moi", "dang_xu_ly", "da_tra_loi", "da_dong", name="trangthaiphananh"),
            nullable=False,
        ),
        sa.Column(
            "trang_thai_kiem_duyet",
            sa.Enum("cho_duyet", "cho_phep", "can_nguoi_duyet", "chan", name="trangthaikiemduyet"),
            nullable=False,
        ),
        sa.Column("so_dong_tinh", sa.Integer(), nullable=False),
        sa.Column("loi_giai_id", sa.String(length=32), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["loi_giai_id"],
            ["loi_giai.id"],
        ),
        sa.ForeignKeyConstraint(
            ["nguoi_gui_id"],
            ["nguoi_dung.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_phan_anh_loi_giai_id"), "phan_anh", ["loi_giai_id"], unique=False)
    op.create_index(op.f("ix_phan_anh_nguoi_gui_id"), "phan_anh", ["nguoi_gui_id"], unique=False)
    op.create_table(
        "tin_nhan",
        sa.Column("hoi_thoai_id", sa.String(length=32), nullable=False),
        sa.Column(
            "vai", sa.Enum("nguoi_dung", "tro_ly", "he_thong", name="vaitinnhan"), nullable=False
        ),
        sa.Column("noi_dung", sa.Text(), nullable=False),
        sa.Column("anh_url", sa.String(length=500), nullable=True),
        sa.Column("model_dung", sa.String(length=100), nullable=True),
        sa.Column("token_vao", sa.Integer(), nullable=False),
        sa.Column("token_ra", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["hoi_thoai_id"],
            ["hoi_thoai.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tin_nhan_hoi_thoai_id"), "tin_nhan", ["hoi_thoai_id"], unique=False)
    op.create_table(
        "binh_luan",
        sa.Column("phan_anh_id", sa.String(length=32), nullable=False),
        sa.Column("nguoi_dang_id", sa.String(length=32), nullable=True),
        sa.Column(
            "vai_tro_nguoi_dang",
            sa.Enum("hoc_sinh", "phu_huynh", "hlv", "bien_tap", "quan_tri", name="vaitro"),
            nullable=True,
        ),
        sa.Column("la_phan_hoi_chinh_thuc", sa.Boolean(), nullable=False),
        sa.Column("noi_dung", sa.Text(), nullable=False),
        sa.Column(
            "trang_thai_kiem_duyet",
            sa.Enum("cho_duyet", "cho_phep", "can_nguoi_duyet", "chan", name="trangthaikiemduyet"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["nguoi_dang_id"],
            ["nguoi_dung.id"],
        ),
        sa.ForeignKeyConstraint(
            ["phan_anh_id"],
            ["phan_anh.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_binh_luan_nguoi_dang_id"), "binh_luan", ["nguoi_dang_id"], unique=False
    )
    op.create_index(op.f("ix_binh_luan_phan_anh_id"), "binh_luan", ["phan_anh_id"], unique=False)
    op.create_table(
        "ket_qua_kiem_chung",
        sa.Column("tin_nhan_id", sa.String(length=32), nullable=True),
        sa.Column("loi_giai_id", sa.String(length=32), nullable=True),
        sa.Column(
            "phuong_phap",
            sa.Enum("sympy", "rag", "cross_check", "proof", "nguoi", name="phuongphapkiemchung"),
            nullable=False,
        ),
        sa.Column(
            "trang_thai",
            sa.Enum("dung", "nghi_van", "sai", "khong_du_can_cu", name="trangthaikiemchung"),
            nullable=False,
        ),
        sa.Column(
            "pham_vi_da_kiem",
            sa.Enum("tinh_toan", "khai_niem", name="phamvikiemchung"),
            nullable=False,
        ),
        sa.Column("do_tin_cay", sa.Float(), nullable=True),
        sa.Column("can_nguoi_duyet", sa.Boolean(), nullable=False),
        sa.Column("chi_tiet", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["loi_giai_id"],
            ["loi_giai.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tin_nhan_id"],
            ["tin_nhan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ket_qua_kiem_chung_loi_giai_id"),
        "ket_qua_kiem_chung",
        ["loi_giai_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ket_qua_kiem_chung_tin_nhan_id"),
        "ket_qua_kiem_chung",
        ["tin_nhan_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ket_qua_kiem_chung_tin_nhan_id"), table_name="ket_qua_kiem_chung")
    op.drop_index(op.f("ix_ket_qua_kiem_chung_loi_giai_id"), table_name="ket_qua_kiem_chung")
    op.drop_table("ket_qua_kiem_chung")
    op.drop_index(op.f("ix_binh_luan_phan_anh_id"), table_name="binh_luan")
    op.drop_index(op.f("ix_binh_luan_nguoi_dang_id"), table_name="binh_luan")
    op.drop_table("binh_luan")
    op.drop_index(op.f("ix_tin_nhan_hoi_thoai_id"), table_name="tin_nhan")
    op.drop_table("tin_nhan")
    op.drop_index(op.f("ix_phan_anh_nguoi_gui_id"), table_name="phan_anh")
    op.drop_index(op.f("ix_phan_anh_loi_giai_id"), table_name="phan_anh")
    op.drop_table("phan_anh")
    op.drop_index(op.f("ix_thanh_toan_nguoi_dung_id"), table_name="thanh_toan")
    op.drop_table("thanh_toan")
    op.drop_index(op.f("ix_loi_giai_de_bai_id"), table_name="loi_giai")
    op.drop_table("loi_giai")
    op.drop_index(op.f("ix_hoi_thoai_nguoi_dung_id"), table_name="hoi_thoai")
    op.drop_table("hoi_thoai")
    op.drop_table("ho_so_hoc_sinh")
    op.drop_index(op.f("ix_han_muc_nguoi_dung_id"), table_name="han_muc")
    op.drop_table("han_muc")
    op.drop_index(op.f("ix_goi_nguoi_dung_id"), table_name="goi")
    op.drop_table("goi")
    op.drop_index(op.f("ix_nguoi_dung_so_dien_thoai"), table_name="nguoi_dung")
    op.drop_index(op.f("ix_nguoi_dung_email"), table_name="nguoi_dung")
    op.drop_table("nguoi_dung")
    op.drop_table("de_bai")
    # ### end Alembic commands ###
