"""B16 billing: thanh_toan.goi_muon

Revision ID: d6e1d263a20a
Revises: 2257fa958ec4
Create Date: 2026-06-26 23:55:26.149342

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d6e1d263a20a"
down_revision: Union[str, None] = "2257fa958ec4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("thanh_toan", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "goi_muon", sa.Enum("free", "standard", "premium", name="loaigoi"), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("thanh_toan", schema=None) as batch_op:
        batch_op.drop_column("goi_muon")

    # ### end Alembic commands ###
