"""B32 community: dong_tinh thong_bao bo_hoi_quy

Revision ID: f42787e4b46a
Revises: b4a123c47c07
Create Date: 2026-06-27 00:38:54.515216

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f42787e4b46a"
down_revision: Union[str, None] = "b4a123c47c07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "thong_bao",
        sa.Column("nguoi_dung_id", sa.String(length=32), nullable=False),
        sa.Column("noi_dung", sa.Text(), nullable=False),
        sa.Column("da_doc", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["nguoi_dung_id"],
            ["nguoi_dung.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("thong_bao", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_thong_bao_nguoi_dung_id"), ["nguoi_dung_id"], unique=False
        )

    op.create_table(
        "bo_hoi_quy",
        sa.Column("nguon_phan_anh_id", sa.String(length=32), nullable=True),
        sa.Column("mo_ta", sa.Text(), nullable=False),
        sa.Column("nhan", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["nguon_phan_anh_id"],
            ["phan_anh.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dong_tinh",
        sa.Column("nguoi_dung_id", sa.String(length=32), nullable=False),
        sa.Column("phan_anh_id", sa.String(length=32), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["nguoi_dung_id"],
            ["nguoi_dung.id"],
        ),
        sa.ForeignKeyConstraint(
            ["phan_anh_id"],
            ["phan_anh.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nguoi_dung_id", "phan_anh_id", name="uq_dong_tinh_nguoi_pa"),
    )
    with op.batch_alter_table("dong_tinh", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_dong_tinh_phan_anh_id"), ["phan_anh_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dong_tinh", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dong_tinh_phan_anh_id"))

    op.drop_table("dong_tinh")
    op.drop_table("bo_hoi_quy")
    with op.batch_alter_table("thong_bao", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_thong_bao_nguoi_dung_id"))

    op.drop_table("thong_bao")
    # ### end Alembic commands ###
