"""B22 metrics: do_luong_hoc

Revision ID: fde45a745e8d
Revises: d6e1d263a20a
Create Date: 2026-06-27 00:10:02.670318

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fde45a745e8d"
down_revision: Union[str, None] = "d6e1d263a20a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "do_luong_hoc",
        sa.Column("nguoi_dung_id", sa.String(length=32), nullable=False),
        sa.Column(
            "giai_doan", sa.Enum("pre", "post", "retention", name="giaidoando"), nullable=False
        ),
        sa.Column("diem", sa.Float(), nullable=False),
        sa.Column("tat_ai", sa.Boolean(), nullable=False),
        sa.Column("nhom", sa.Enum("app", "doi_chung", name="nhomthunghiem"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["nguoi_dung_id"],
            ["nguoi_dung.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("do_luong_hoc", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_do_luong_hoc_nguoi_dung_id"), ["nguoi_dung_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("do_luong_hoc", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_do_luong_hoc_nguoi_dung_id"))

    op.drop_table("do_luong_hoc")
    # ### end Alembic commands ###
